### ISSUE TITLE
runtime Errors

### ISSUE THREAD

**Issue by tbaror** [Napsty/check_esxi_hardware#20]
Hello , 
Just installed the plugin under Ubuntu 16.04 including prerequisite (pywbem), when running the script on   on terminal i get following error below , didn't found any earlier  reference to it ,
Please advice
Thanks 
`Traceback (most recent call last):
  File "./check_esxi_hardware.py", line 249, in <module>
    import pywbem
  File "/usr/local/lib/python2.7/dist-packages/pywbem/__init__.py", line 36, in <module>
    from .cim_operations import *  # noqa: F403,F401
  File "/usr/local/lib/python2.7/dist-packages/pywbem/cim_operations.py", line 161, in <module>
    from .cim_http import get_object_header, wbem_request
  File "/usr/local/lib/python2.7/dist-packages/pywbem/cim_http.py", line 60, in <module>
    from M2Crypto import SSL           # pylint: disable=wrong-import-position
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/__init__.py", line 26, in <module>
    from M2Crypto import (ASN1, AuthCookie, BIO, BN, DH, DSA, EVP, Engine, Err,
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/ASN1.py", line 15, in <module>
    from M2Crypto import BIO, m2, util
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/BIO.py", line 10, in <module>
    from M2Crypto import m2, util
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/m2.py", line 30, in <module>
    from M2Crypto._m2crypto import *
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/_m2crypto.py", line 26, in <module>
    __m2crypto = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/_m2crypto.py", line 22, in swig_import_helper
    _mod = imp.load_module('__m2crypto', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/M2Crypto/__m2crypto.so: undefined symbol: SSLv3_method`

**Comment by Napsty** [comment]
The pywbem installation on that host seems to be broken. Please reinstall or check on https://github.com/pywbem/pywbem.
