### ISSUE TITLE
Error on importing pywbem.cim_http and pywbem.cim_operations

### ISSUE THREAD

**Issue by moonbaseDelta** [Napsty/check_esxi_hardware#54]
Hi, I've got those import errors, but investigating current version of pywbem gived me a clue that those two should be `pywbem._cim_http` and `pywbem._cim_operations`. That fix inside code worked for py3 and py2.

**Comment by Napsty** [comment]
Sorry, not sure I understand the issue. So what is the error you experienced? Did you fix the code yourself or was something inside pywbem broken and fixed?

**Comment by philrandal** [comment]
The API in pywbem changed in 1.0.0.

From https://pywbem.readthedocs.io/en/stable_1.1/changes.html#pywbem-1-0-0b1

"Made all sub-namespaces within the pywbem namespace private, except for pywbem.config. Specifically, renamed the following modules by prepending an underscore character: cim_constants.py, cim_http.py, cim_obj.py, cim_operations.py, cim_types.py, cim_xml.py, exceptions.py, mof_compiler.py, moflextab.py, mofparsetab.py, tupleparse.py, tupletree.py. Using these sub-namespaces had been deprecated in pywbem 0.8.0.

This change is compatible for users that followed the recommendation to import only the symbols from the pywbem namespace. Users that imported symbols from these sub-namespace should now import them from the pywbem namespace. If you miss a symbol in the pywbem namespace, it was likely a symbol that is not part of the public pywbem API. (See issue #1925)"

**Comment by philrandal** [comment]
workaround is to stick with an earlier version of pywbem, e.g.

`pip install pywbem==0.17.6`

**Comment by philrandal** [comment]
Or apply this patch, which should work with pywbem 0.8.0 and later:

`]# diff -Naur check_esxi_hardware.py check_esxi_hardware.py.new
--- check_esxi_hardware.py      2021-06-03 09:01:40.092496740 +0100
+++ check_esxi_hardware.py.new  2021-06-03 08:53:03.202992912 +0100
@@ -738,7 +738,7 @@
 if vendor=='auto':
   try:
     c=wbemclient.EnumerateInstances('CIM_Chassis')
-  except pywbem.cim_operations.CIMError as args:
+  except pywbem._cim_operations.CIMError as args:
     if ( args[1].find('Socket error') >= 0 ):
       print("UNKNOWN: {}".format(args))
       sys.exit (ExitUnknown)
@@ -751,7 +751,7 @@
     GlobalStatus = ExitUnknown
     print("UNKNOWN: {}".format(args))
     sys.exit (GlobalStatus)
-  except pywbem.cim_http.AuthError as arg:
+  except pywbem._cim_http.AuthError as arg:
     verboseoutput("Global exit set to UNKNOWN")
     GlobalStatus = ExitUnknown
     print("UNKNOWN: Authentication Error")
@@ -773,7 +773,7 @@
   verboseoutput("Check classe "+classe)
   try:
     instance_list = wbemclient.EnumerateInstances(classe)
-  except pywbem.cim_operations.CIMError as args:
+  except pywbem._cim_operations.CIMError as args:
     if ( args[1].find('Socket error') >= 0 ):
       print("UNKNOWN: {}".format(args))
       sys.exit (ExitUnknown)
@@ -786,7 +786,7 @@
     GlobalStatus = ExitUnknown
     print("UNKNOWN: {}".format(args))
     sys.exit (GlobalStatus)
-  except pywbem.cim_http.AuthError as arg:
+  except pywbem._cim_http.AuthError as arg:
     verboseoutput("Global exit set to UNKNOWN")
     GlobalStatus = ExitUnknown
     print("UNKNOWN: Authentication Error")
`

**Comment by Napsty** [comment]
Thx @philrandal for sharing the knowledge. Will take a closer look at this. Maybe either ditch support for the old pywbem 0.7.x or have the connection check twice depending on the pywbem version.

**Comment by philrandal** [comment]
You could have separate try ... except blocks depending on pywbem version, for backwards compatibility

**Comment by Napsty** [comment]
Yes, that's what I meant with "check twice depending on the pywbem version". It's basically only RHEL and CentOS which still ship the old pywbem :-/

**Comment by n-rodriguez** [comment]
Hi there! I think this issue can be closed.

**Comment by n-rodriguez** [comment]
@Napsty hi there! can you please reopen this issue? I thought it was fixed with the latest version but it's not the case 😢 

```sh
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/check_esxi_hardware.py", line 757, in <module>
    except pywbem.cim_operations.CIMError as args:
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pywbem' has no attribute 'cim_operations'. Did you mean: '_cim_operations'?
```

**Comment by Napsty** [comment]
Will look at it soon, should be easier to fix now that old version compatibilities for python2 and pywbem 0.7.0 have been removed.

**Comment by philrandal** [comment]
This patch should fix it:

`# diff -Naur check_esxi_hardware.py.old check_esxi_hardware.py
--- check_esxi_hardware.py.old  2024-12-09 13:53:59.043000002 +0000
+++ check_esxi_hardware.py      2024-12-09 13:56:05.995755134 +0000
@@ -754,7 +754,7 @@
 if vendor=='auto':
   try:
     c=wbemclient.EnumerateInstances('CIM_Chassis')
-  except pywbem.cim_operations.CIMError as args:
+  except pywbem._cim_operations.CIMError as args:
     if ( args[1].find('Socket error') >= 0 ):
       print("UNKNOWN: {}".format(args))
       sys.exit (ExitUnknown)
@@ -767,7 +767,7 @@
     GlobalStatus = ExitUnknown
     print("UNKNOWN: {}".format(args))
     sys.exit (GlobalStatus)
-  except pywbem.cim_http.AuthError as arg:
+  except pywbem._cim_http.AuthError as arg:
     verboseoutput("Global exit set to UNKNOWN")
     GlobalStatus = ExitUnknown
     print("UNKNOWN: Authentication Error")
`

**Comment by Napsty** [comment]
@n-rodriguez can you try with https://raw.githubusercontent.com/Napsty/check_esxi_hardware/refs/heads/issue-54/check_esxi_hardware.py ?

**Comment by Napsty** [comment]
Tested on Ubuntu 24.04 with pywbem 1.7.2, works fine:

```
$ ./check_esxi_hardware.py -H myesxi -U monitoring -P wrongpw -v
20250214 08:13:41 LCD Status: True
20250214 08:13:41 Chassis Intrusion Status: True
20250214 08:13:41 Found pywbem version 1.7.2
20250214 08:13:41 Connection to https://myesxi
20250214 08:13:41 Check classe OMC_SMASHFirmwareIdentity
20250214 08:13:43 Global exit set to UNKNOWN
UNKNOWN: Authentication Error
```

Also tested on Rocky 8 (pywbem 0.11.0) and Rocky 9 (0.15.0). Both of them use pywbem versions below 1.0.0, if installed using `dnf`. Here the updated plugin runs into an exception:

```
# ./check_esxi_hardware.py -H myesxi -U monitoring -P wrongpw -v
20250214 07:02:27 LCD Status: True
20250214 07:02:27 Chassis Intrusion Status: True
20250214 07:02:27 Found pywbem version 0.15.0
20250214 07:02:27 Connection to https://myesxi
20250214 07:02:27 Check classe OMC_SMASHFirmwareIdentity
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pywbem/cim_http.py", line 818, in wbem_request
    client.endheaders()
  File "/usr/lib64/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/site-packages/pywbem/cim_http.py", line 482, in send
    self.connect()  # pylint: disable=no-member
  File "/usr/lib/python3.9/site-packages/pywbem/cim_http.py", line 649, in connect
    return self.sock.connect((self.host, self.port))
  File "/usr/lib64/python3.9/ssl.py", line 1376, in connect
    self._real_connect(addr, False)
  File "/usr/lib64/python3.9/ssl.py", line 1363, in _real_connect
    super().connect(addr)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/./check_esxi_hardware.py", line 795, in <module>
    instance_list = wbemclient.EnumerateInstances(classe)
  File "/usr/lib/python3.9/site-packages/pywbem/cim_operations.py", line 2458, in EnumerateInstances
    result = self._imethodcall(
  File "/usr/lib/python3.9/site-packages/pywbem/cim_operations.py", line 1728, in _imethodcall
    reply_data, self._last_server_response_time = wbem_request(
  File "/usr/lib/python3.9/site-packages/pywbem/cim_http.py", line 1006, in wbem_request
    raise ConnectionError(
pywbem.exceptions.ConnectionError: Socket error: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/./check_esxi_hardware.py", line 796, in <module>
    except pywbem._cim_operations.CIMError as args:
AttributeError: module 'pywbem' has no attribute '_cim_operations'
```

So I need to adjust this a little bit to cover older pywbem versions, as long as they're around.

**Comment by Napsty** [comment]
Got it working, improved exception handling, supports now older and newer pywbem exception handling. 
Also added HTTPError handling. This makes sense when the plugin is launched against a HTTP listener (e.g. ESXI:443), which has no CIM elements showing up.

**Comment by Napsty** [comment]
@moonbaseDelta @n-rodriguez Please try with https://raw.githubusercontent.com/Napsty/check_esxi_hardware/refs/heads/issue-54/check_esxi_hardware.py

Worked fine here, successfully tested on Rocky Linux 8, Ubuntu 20.04 and Ubuntu 24.04.

**Comment by philrandal** [comment]
Looks good to me.

Tested on AlmaLinux 8.
