### ISSUE TITLE
ImportError: No module named pywbem | Ubuntu 20.04.03

### ISSUE THREAD

**Issue by vias79** [Napsty/check_esxi_hardware#62]
**Before actually creating a new issue**
I confirm, I have read the FAQ (https://www.claudiokuenzler.com/blog/308/check-esxi-hardware-faq-frequently-asked-questions): Y

**Describe the bug**
Same problem as bug report 53 (https://github.com/Napsty/check_esxi_hardware/issues/53), script can't seem to find pywbem module. Using Ubuntu 20.04.03.
```
root@myserver:~# /usr/lib/nagios/plugins/check_esxi_hardware.py -H myserver -U root -P mypwd --no-intrusion
Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/check_esxi_hardware.py", line 292, in <module>
    import pywbem
ImportError: No module named pywbem
```

**Versions:**
 - check_esxi_hardware plugin: **20210809**
 - pywbem: **1.4.1**
```
 root@myserver:~# pip list pywbem | grep pywbem
pywbem                 1.4.1
```

 - Python: 2.7.18 and 3.8.10
```
root@myserver:~# python -V
Python 2.7.18
root@myserver:~# python3 -V
Python 3.8.10
```

**Additional context**
I've tried installing sblim-wbemcli but it doesn't seem to work. I've also logged out and even restarted the server.

```
root@myserver:~# apt install python-pywbem
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python-pywbem is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  sblim-wbemcli

E: Package 'python-pywbem' has no installation candidate
root@myserver:~# apt install sblim-wbemcli
Reading package lists... Done
Building dependency tree
Reading state information... Done
sblim-wbemcli is already the newest version (1.6.3-2build1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@myserver:~#
root@myserver:~# /usr/lib/nagios/plugins/check_esxi_hardware.py -H myserver -U root -P mypwd --no-intrusion
Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/check_esxi_hardware.py", line 292, in <module>
    import pywbem
ImportError: No module named pywbem
```

I've run pip install aswell

```
root@myserver:~# pip install pywbem
Requirement already satisfied: pywbem in /usr/local/lib/python3.8/dist-packages (1.4.1)
Requirement already satisfied: requests>=2.22.0 in /usr/lib/python3/dist-packages (from pywbem) (2.22.0)
Requirement already satisfied: ply>=3.10 in /usr/local/lib/python3.8/dist-packages (from pywbem) (3.11)
Requirement already satisfied: urllib3>=1.25.9 in /usr/local/lib/python3.8/dist-packages (from pywbem) (1.26.8)
Requirement already satisfied: yamlloader>=0.5.5 in /usr/local/lib/python3.8/dist-packages (from pywbem) (1.1.0)
Requirement already satisfied: nocaselist>=1.0.3 in /usr/local/lib/python3.8/dist-packages (from pywbem) (1.0.4)
Requirement already satisfied: nocasedict>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from pywbem) (1.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/lib/python3/dist-packages (from pywbem) (1.14.0)
Requirement already satisfied: PyYAML>=5.3.1 in /usr/lib/python3/dist-packages (from pywbem) (5.3.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@myserver:~#
```

The files seems to be there

```
root@myserver:~# ls -l /usr/local/lib/python3.8/dist-packages
total 60
drwxr-sr-x 3 root staff 4096 Feb  4 13:29 nocasedict
drwxr-sr-x 2 root staff 4096 Feb  4 13:29 nocasedict-1.0.2.dist-info
drwxr-sr-x 3 root staff 4096 Feb  4 13:29 nocaselist
drwxr-sr-x 2 root staff 4096 Feb  4 13:29 nocaselist-1.0.4.dist-info
drwxr-sr-x 5 root staff 4096 Feb  4 13:47 pip
drwxr-sr-x 2 root staff 4096 Feb  4 13:47 pip-22.0.3.dist-info
drwxr-sr-x 3 root staff 4096 Feb  4 13:29 ply
drwxr-sr-x 2 root staff 4096 Feb  4 13:29 ply-3.11.dist-info
drwxr-sr-x 3 root staff 4096 Feb  4 13:29 pywbem
drwxr-sr-x 2 root staff 4096 Feb  4 13:29 pywbem-1.4.1.dist-info
drwxr-sr-x 3 root staff 4096 Feb  4 13:29 pywbem_mock
drwxr-sr-x 6 root staff 4096 Feb  4 13:29 urllib3
drwxr-sr-x 2 root staff 4096 Feb  4 13:29 urllib3-1.26.8.dist-info
drwxr-sr-x 4 root staff 4096 Feb  4 13:29 yamlloader
drwxr-sr-x 2 root staff 4096 Feb  4 13:29 yamlloader-1.1.0.dist-info
root@myserver:~# ls -l /usr/local/lib/python3.8/dist-packages/pywbem
total 1588
-rw-r--r-- 1 root staff  10821 Feb  4 13:29 _cim_constants.py
-rw-r--r-- 1 root staff  17511 Feb  4 13:29 _cim_http.py
-rw-r--r-- 1 root staff 307002 Feb  4 13:29 _cim_obj.py
-rw-r--r-- 1 root staff 444445 Feb  4 13:29 _cim_operations.py
-rw-r--r-- 1 root staff  50789 Feb  4 13:29 _cim_types.py
-rw-r--r-- 1 root staff  56118 Feb  4 13:29 _cim_xml.py
-rw-r--r-- 1 root staff   1971 Feb  4 13:29 _cliutils.py
-rw-r--r-- 1 root staff   5176 Feb  4 13:29 config.py
-rw-r--r-- 1 root staff  25884 Feb  4 13:29 _exceptions.py
-rw-r--r-- 1 root staff   1685 Feb  4 13:29 _features.py
-rw-r--r-- 1 root staff   3655 Feb  4 13:29 __init__.py
-rw-r--r-- 1 root staff  45720 Feb  4 13:29 _listener.py
-rw-r--r-- 1 root staff  21549 Feb  4 13:29 _logging.py
-rw-r--r-- 1 root staff 114278 Feb  4 13:29 _mof_compiler.py
-rw-r--r-- 1 root staff   2648 Feb  4 13:29 _moflextab.py
-rw-r--r-- 1 root staff  70070 Feb  4 13:29 _mofparsetab.py
-rw-r--r-- 1 root staff   3522 Feb  4 13:29 _nocasedict.py
drwxr-sr-x 2 root staff   4096 Feb  4 13:29 __pycache__
-rw-r--r-- 1 root staff  44071 Feb  4 13:29 _recorder.py
-rw-r--r-- 1 root staff  55039 Feb  4 13:29 _server.py
-rw-r--r-- 1 root staff  29709 Feb  4 13:29 _statistics.py
-rw-r--r-- 1 root staff  63685 Feb  4 13:29 _subscription_manager.py
-rw-r--r-- 1 root staff  91426 Feb  4 13:29 _tupleparse.py
-rw-r--r-- 1 root staff  20208 Feb  4 13:29 _tupletree.py
-rw-r--r-- 1 root staff  25979 Feb  4 13:29 _units.py
-rw-r--r-- 1 root staff  13309 Feb  4 13:29 _utils.py
-rw-r--r-- 1 root staff  32939 Feb  4 13:29 _valuemapping.py
-rw-r--r-- 1 root staff   1192 Feb  4 13:29 _version.py
-rw-r--r-- 1 root staff   2694 Feb  4 13:29 _warnings.py
root@myserver:~#

```

I don't think I have any virtual enviroments.

Any tips appreciated :)

**Comment by Napsty** [comment]
Hello. You missed one little tiny note in the documentation (https://www.claudiokuenzler.com/monitoring-plugins/check_esxi_hardware.php):

> Note that the pywbem package was removed in Debian >=11 and Ubuntu >=20.04, use pip/pip3 in this case.

So you need to install pywbem with `pip3 install pywbem`.

**Comment by vias79** [comment]
Wow thank you for the quick response, I tried that. Sadly it doesn't work.

```
root@myserver:~# pip3 install pywbem
Requirement already satisfied: pywbem in /usr/local/lib/python3.8/dist-packages (1.4.1)
Requirement already satisfied: nocaselist>=1.0.3 in /usr/local/lib/python3.8/dist-packages (from pywbem) (1.0.4)
Requirement already satisfied: yamlloader>=0.5.5 in /usr/local/lib/python3.8/dist-packages (from pywbem) (1.1.0)
Requirement already satisfied: requests>=2.22.0 in /usr/lib/python3/dist-packages (from pywbem) (2.22.0)
Requirement already satisfied: six>=1.14.0 in /usr/lib/python3/dist-packages (from pywbem) (1.14.0)
Requirement already satisfied: urllib3>=1.25.9 in /usr/local/lib/python3.8/dist-packages (from pywbem) (1.26.8)
Requirement already satisfied: ply>=3.10 in /usr/local/lib/python3.8/dist-packages (from pywbem) (3.11)
Requirement already satisfied: PyYAML>=5.3.1 in /usr/lib/python3/dist-packages (from pywbem) (5.3.1)
Requirement already satisfied: nocasedict>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from pywbem) (1.0.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@myserver:~#
root@myserver:~# /usr/lib/nagios/plugins/check_esxi_hardware.py -H myserver -U root -P mypwd --no-intrusion
Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/check_esxi_hardware.py", line 292, in <module>
    import pywbem
ImportError: No module named pywbem
```

**Comment by Napsty** [comment]
Interesting! Which pywbem version did pip3 install here? You can use `pip3 list`.

Can you try with a known to be working pywbem version (https://www.claudiokuenzler.com/blog/1110/check_esxi_hardware-esxi-compatibility-matrix-list)? 

```
pip3 install pywbem=1.2.0
```

Maybe there's a dependency problem in the newest version.

**Comment by Napsty** [comment]
Another possibility: Your OS is failing back to python2 when the plugin is executed - where pywbem might not exist. Try to enforce python3 to see if this works:

```
root@myserver:~# /usr/bin/python3 /usr/lib/nagios/plugins/check_esxi_hardware.py -H myserver -U root -P mypwd --no-intrusion
```

**Comment by vias79** [comment]
root@myserver:~# pip3 list | grep pywbem
pywbem                 1.4.1

Yes running it with python3 seemed to do the trick, got another weird error though :)
```
root@myserver:~# /usr/bin/python3 /usr/lib/nagios/plugins/check_esxi_hardware.py -H myserver -U root -P mypwd --no-intrusion
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
OK - Server: Default string X10DRi s/n: Default string System BIOS: 3.1 2018-09-14
myserver@myserver:~$
```

**Comment by Napsty** [comment]
OK so you either need to change /usr/bin/python to point to python3, for example using `alternatives` (see https://www.claudiokuenzler.com/blog/1174/how-to-change-php-version-command-line-cli-alternatives for an example) or you could change the first line in the plugin https://github.com/Napsty/check_esxi_hardware/blob/master/check_esxi_hardware.py#L1 from `#!/usr/bin/python` to `#!/usr/bin/python3`.

The warning you see is because of this: https://www.claudiokuenzler.com/blog/1114/urllib3-or-chardet-doesnt-match-a-supported-version-check-esxi-hardware

**Comment by vias79** [comment]
Thank you for the help
