### ISSUE TITLE
check_esxi_hardware.py fails after ESXI upgrade

### ISSUE THREAD

**Issue by Palaniyappanpl** [Napsty/check_esxi_hardware#66]
Hi Claudio Kuenzler,

We have upgrade the ESXI from 6.7 to 7.0.3 19482537. The plugin stopped working and returns an "UnAuthorized" error, Kindly advise.

Python Version : 3.8
Pywbem Version : 0.12.0

[~@node01]# /usr/local/nagios/libexec/check_esxi_hardware.py -H "172.16.10.11" -U file:/usr/local/nagios/etc/.esxiauth1 -P file:/usr/local/nagios/etc/.esxiauth1 -V dell --perfdata
Traceback (most recent call last):
  File "/usr/local/nagios/libexec/check_esxi_hardware.py", line 780, in <module>
    instance_list = wbemclient.EnumerateInstances(classe)
  File "/usr/local/lib/python3.8/site-packages/pywbem/_cim_operations.py", line 3052, in EnumerateInstances
    result = self._imethodcall(
  File "/usr/local/lib/python3.8/site-packages/pywbem/_cim_operations.py", line 1949, in _imethodcall
    reply_data, self._last_server_response_time = wbem_request(
  File "/usr/local/lib/python3.8/site-packages/pywbem/_cim_http.py", line 568, in wbem_request
    raise AuthError(msg, conn_id=conn.conn_id)
pywbem._exceptions.AuthError: WBEM server returned HTTP status 401 (Unauthorized). This is most likely an issue with userid/password, but for servers that implement resource access control it might also be an issue with the permissions of the userid.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/nagios/libexec/check_esxi_hardware.py", line 781, in <module>
    except pywbem.cim_operations.CIMError as args:
AttributeError: module 'pywbem' has no attribute 'cim_operations'

**Comment by Palaniyappanpl** [comment]
Hi Claudio Kuenzler,

Any findings please.

**Comment by Napsty** [comment]
@Palaniyappanpl I personally have not much time these days and need to finish paid work first. I will look at it as soon as I have time. Please also check the [check_esxi_hardware monitoring plugin compatibility list](https://www.claudiokuenzler.com/blog/1110/check_esxi_hardware-esxi-compatibility-matrix-list).
Or, if it's really urgent, request a paid modification on infiniroot.com.

**Comment by Napsty** [comment]
Please run the plugin in verbose mode ( `-v`) and post the output here.

**Comment by lucafwp** [comment]
Hi, same issue on my side.
Here is the output after updating to pywbem 1.6.1:

20230804 15:34:15 LCD Status: True
20230804 15:34:15 Chassis Intrusion Status: True
20230804 15:34:15 Connection to https://x.x.x.x
20230804 15:34:15 Found pywbem version 1.6.1
20230804 15:34:15 Check classe OMC_SMASHFirmwareIdentity
Traceback (most recent call last):
  File "/neteye/shared/monitoring/plugins/check_esxi_hardware.py", line 780, in <module>
    instance_list = wbemclient.EnumerateInstances(classe)
  File "/usr/local/lib/python3.6/site-packages/pywbem/_cim_operations.py", line 3066, in EnumerateInstances
    PropertyList=PropertyList)
  File "/usr/local/lib/python3.6/site-packages/pywbem/_cim_operations.py", line 1956, in _imethodcall
    self, request_data, cimxml_headers)
  File "/usr/local/lib/python3.6/site-packages/pywbem/_cim_http.py", line 501, in wbem_request
    raise pywbem_requests_exception(exc, conn)
pywbem._exceptions.ConnectionError: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/neteye/shared/monitoring/plugins/check_esxi_hardware.py", line 781, in <module>
    except pywbem.cim_operations.CIMError as args:
AttributeError: module 'pywbem' has no attribute 'cim_operations'

**Comment by Napsty** [comment]
@lucafwp  Please open a new issue. The problem this issue is about was after a vSphere / ESXi upgrade. Yours seems to be after an upgrade of the pywbem module.

**Comment by Napsty** [comment]
@Palaniyappanpl The issue you reported is most likely caused by the ESXi upgrade itself. It removes additional local users, which you might have created for CIM monitoring. Please refer to the FAQ (https://www.claudiokuenzler.com/blog/308/check-esxi-hardware-faq-frequently-asked-questions).
