### ISSUE TITLE
 ignore certificate check

### ISSUE THREAD

**Issue by ls440** [Napsty/check_esxi_hardware#67]
Hi

I would like to monitor esxi hardware with out ssl certificate check. is it possible ?

**Comment by ls440** [comment]
^CTraceback (most recent call last):
  File "/usr/lib/nagios/plugins/check_esxi.py", line 804, in <module>
    instance_list = wbemclient.EnumerateInstances(classe)
  File "/usr/local/lib/python2.7/dist-packages/pywbem/_cim_operations.py", line 3060, in EnumerateInstances
    PropertyList=PropertyList)
  File "/usr/local/lib/python2.7/dist-packages/pywbem/_cim_operations.py", line 1950, in _imethodcall
    self, request_data, cimxml_headers)
  File "/usr/local/lib/python2.7/dist-packages/pywbem/_cim_http.py", line 494, in wbem_request
    timeout=(HTTP_CONNECT_TIMEOUT, conn.timeout))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

**Comment by Napsty** [comment]
The plugin is already set up to ignore a certificate verification/validation. 
This is controlled by the `no_verification=True` option which is used in the pywbem.WBEMConnection function.
The error you mentioned above must be caused by something else.
